### ISSUE TITLE
태그 목록 출력하기

### ISSUE THREAD

**Issue by kimdw524** [kimdw524/kimdw524.github.io#7]
## 📌 Summary

태그 목록 출력하기

## 📋 Tasks

- [x] Post에 category 없애기
- [x] 메인 화면에 전체 태그 목록 보여주기
- [x] PostItem에 태그 목록 보여주기
